# -*- coding: utf-8 -*-
"""
Referentiel PAYS officiel (nom <-> ISO 3166-1 alpha-3), resolveur tolerant.

SOURCE : eForms-SDK de l'Office des Publications de l'UE (OP-TED),
codelist `country.gc`. Donnees publiques UE, librement reutilisables
(decision 2011/833/UE) : aucune dependance de code, juste des donnees.

POURQUOI : les mappings nom->ISO3 faits main rataient des variantes
d'orthographe (Irak vs Iraq, Equateur vs Equateur accentue, RDC vs
Republique democratique du Congo), ce qui tuait des leads en silence.
Ce module fournit les 246 formes officielles FR+EN et un resolveur qui
normalise les accents et la casse. Additif : il complete les tables
metier existantes (zones, multiplicateurs), il ne les remplace pas.
"""

import unicodedata


PAYS_FR = {
    "ABW": "Aruba",
    "AFG": "Afghanistan",
    "AGO": "Angola",
    "AIA": "Anguilla",
    "ALA": "Îles Åland",
    "ALB": "Albanie",
    "AND": "Andorre",
    "ARE": "Émirats arabes unis",
    "ARG": "Argentine",
    "ARM": "Arménie",
    "ASM": "Samoa américaines",
    "ATA": "Antarctique",
    "ATF": "Terres australes et antarctiques françaises",
    "ATG": "Antigua-et-Barbuda",
    "AUS": "Australie",
    "AUT": "Autriche",
    "AZE": "Azerbaïdjan",
    "BDI": "Burundi",
    "BEL": "Belgique",
    "BEN": "Bénin",
    "BES": "Bonaire, Saint-Eustache et Saba",
    "BFA": "Burkina Faso",
    "BGD": "Bangladesh",
    "BGR": "Bulgarie",
    "BHR": "Bahreïn",
    "BHS": "Bahamas",
    "BIH": "Bosnie-Herzégovine",
    "BLM": "Saint-Barthélemy",
    "BLR": "Biélorussie",
    "BLZ": "Belize",
    "BMU": "Bermudes",
    "BOL": "Bolivie",
    "BRA": "Brésil",
    "BRB": "Barbade",
    "BRN": "Brunei",
    "BTN": "Bhoutan",
    "BVT": "Île Bouvet",
    "BWA": "Botswana",
    "CAF": "République centrafricaine",
    "CAN": "Canada",
    "CCK": "Îles des Cocos",
    "CHE": "Suisse",
    "CHL": "Chili",
    "CHN": "Chine",
    "CIV": "Côte d’Ivoire",
    "CMR": "Cameroun",
    "COD": "République démocratique du Congo",
    "COG": "Congo",
    "COK": "Îles Cook",
    "COL": "Colombie",
    "COM": "Comores",
    "CPT": "Clipperton",
    "CPV": "Cabo Verde",
    "CRI": "Costa Rica",
    "CUB": "Cuba",
    "CUW": "Curaçao",
    "CXR": "Île Christmas",
    "CYM": "Îles Caïmans",
    "CYP": "Chypre",
    "CZE": "Tchéquie",
    "DEU": "Allemagne",
    "DJI": "Djibouti",
    "DMA": "Dominique",
    "DNK": "Danemark",
    "DOM": "République dominicaine",
    "DZA": "Algérie",
    "ECU": "Équateur",
    "EGY": "Égypte",
    "ERI": "Érythrée",
    "ESH": "Sahara occidental",
    "ESP": "Espagne",
    "EST": "Estonie",
    "ETH": "Éthiopie",
    "FIN": "Finlande",
    "FJI": "Fidji",
    "FLK": "Îles Falkland",
    "FRA": "France",
    "FRO": "Îles Féroé",
    "FSM": "Micronésie",
    "GAB": "Gabon",
    "GBR": "Royaume-Uni",
    "GEO": "Géorgie",
    "GGY": "Guernesey",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GIN": "Guinée",
    "GMB": "Gambie",
    "GNB": "Guinée-Bissau",
    "GNQ": "Guinée équatoriale",
    "GRC": "Grèce",
    "GRD": "Grenade",
    "GRL": "Groenland",
    "GTM": "Guatemala",
    "GUM": "Guam",
    "GUY": "Guyana",
    "HKG": "Hong Kong",
    "HMD": "Îles Heard et McDonald",
    "HND": "Honduras",
    "HRV": "Croatie",
    "HTI": "Haïti",
    "HUN": "Hongrie",
    "IDN": "Indonésie",
    "IMN": "Île de Man",
    "IND": "Inde",
    "IOT": "Territoire britannique de l’océan Indien",
    "IRL": "Irlande",
    "IRN": "Iran",
    "IRQ": "Iraq",
    "ISL": "Islande",
    "ISR": "Israël",
    "ITA": "Italie",
    "JAM": "Jamaïque",
    "JEY": "Jersey",
    "JOR": "Jordanie",
    "JPN": "Japon",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KGZ": "Kirghizstan",
    "KHM": "Cambodge",
    "KIR": "Kiribati",
    "KNA": "Saint-Christophe-et-Niévès",
    "KOR": "Corée du Sud",
    "KWT": "Koweït",
    "LAO": "Laos",
    "LBN": "Liban",
    "LBR": "Liberia",
    "LBY": "Libye",
    "LCA": "Sainte-Lucie",
    "LIE": "Liechtenstein",
    "LKA": "Sri Lanka",
    "LSO": "Lesotho",
    "LTU": "Lituanie",
    "LUX": "Luxembourg",
    "LVA": "Lettonie",
    "MAC": "Macao",
    "MAF": "Saint-Martin",
    "MAR": "Maroc",
    "MCO": "Monaco",
    "MDA": "Moldavie",
    "MDG": "Madagascar",
    "MDV": "Maldives",
    "MEX": "Mexique",
    "MHL": "Îles Marshall",
    "MKD": "Macédoine du Nord",
    "MLI": "Mali",
    "MLT": "Malte",
    "MMR": "Myanmar/Birmanie",
    "MNE": "Monténégro",
    "MNG": "Mongolie",
    "MNP": "Îles Mariannes du Nord",
    "MOZ": "Mozambique",
    "MRT": "Mauritanie",
    "MSR": "Montserrat",
    "MUS": "Maurice",
    "MWI": "Malawi",
    "MYS": "Malaisie",
    "NAM": "Namibie",
    "NCL": "Nouvelle-Calédonie",
    "NER": "Niger",
    "NFK": "Île Norfolk",
    "NGA": "Nigeria",
    "NIC": "Nicaragua",
    "NIU": "Niué",
    "NLD": "Pays-Bas",
    "NOR": "Norvège",
    "NPL": "Népal",
    "NRU": "Nauru",
    "NZL": "Nouvelle-Zélande",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PCN": "Îles Pitcairn",
    "PER": "Pérou",
    "PHL": "Philippines",
    "PLW": "Palaos",
    "PNG": "Papouasie - Nouvelle-Guinée",
    "POL": "Pologne",
    "PRI": "Porto Rico",
    "PRK": "Corée du Nord",
    "PRT": "Portugal",
    "PRY": "Paraguay",
    "PSE": "Palestine",
    "PYF": "Polynésie française",
    "QAT": "Qatar",
    "ROU": "Roumanie",
    "RUS": "Russie",
    "RWA": "Rwanda",
    "SAU": "Arabie saoudite",
    "SDN": "Soudan",
    "SEN": "Sénégal",
    "SGP": "Singapour",
    "SGS": "Îles Géorgie du Sud et Sandwich du Sud",
    "SHN": "Sainte-Hélène, Ascension et Tristan da Cunha",
    "SJM": "Svalbard et Jan Mayen",
    "SLB": "Îles Salomon",
    "SLE": "Sierra Leone",
    "SLV": "El Salvador",
    "SMR": "Saint-Marin",
    "SOM": "Somalie",
    "SPM": "Saint-Pierre-et-Miquelon",
    "SRB": "Serbie",
    "SSD": "Soudan du Sud",
    "STP": "Sao Tomé-et-Principe",
    "SUR": "Suriname",
    "SVK": "Slovaquie",
    "SVN": "Slovénie",
    "SWE": "Suède",
    "SWZ": "Eswatini",
    "SXM": "Sint-Maarten",
    "SYC": "Seychelles",
    "SYR": "Syrie",
    "TCA": "Îles Turks-et-Caïcos",
    "TCD": "Tchad",
    "TGO": "Togo",
    "THA": "Thaïlande",
    "TJK": "Tadjikistan",
    "TKL": "Tokélaou",
    "TKM": "Turkménistan",
    "TLS": "Timor-Oriental",
    "TON": "Tonga",
    "TTO": "Trinité-et-Tobago",
    "TUN": "Tunisie",
    "TUR": "Turquie",
    "TUV": "Tuvalu",
    "TWN": "Taïwan",
    "TZA": "Tanzanie",
    "UGA": "Ouganda",
    "UKR": "Ukraine",
    "UMI": "Îles mineures éloignées des États-Unis",
    "URY": "Uruguay",
    "USA": "États-Unis",
    "UZB": "Ouzbékistan",
    "VAT": "Saint-Siège",
    "VCT": "Saint-Vincent-et-les-Grenadines",
    "VEN": "Venezuela",
    "VGB": "Îles Vierges britanniques",
    "VIR": "Îles Vierges américaines",
    "VNM": "Viêt Nam",
    "VUT": "Vanuatu",
    "WLF": "Wallis-et-Futuna",
    "WSM": "Samoa",
    "XKX": "Kosovo",
    "YEM": "Yémen",
    "ZAF": "Afrique du Sud",
    "ZMB": "Zambie",
    "ZWE": "Zimbabwe",
}

PAYS_EN = {
    "ABW": "Aruba",
    "AFG": "Afghanistan",
    "AGO": "Angola",
    "AIA": "Anguilla",
    "ALA": "Åland Islands",
    "ALB": "Albania",
    "AND": "Andorra",
    "ARE": "United Arab Emirates",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ASM": "American Samoa",
    "ATA": "Antarctica",
    "ATF": "French Southern and Antarctic Lands",
    "ATG": "Antigua and Barbuda",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BDI": "Burundi",
    "BEL": "Belgium",
    "BEN": "Benin",
    "BES": "Bonaire, Sint Eustatius and Saba",
    "BFA": "Burkina Faso",
    "BGD": "Bangladesh",
    "BGR": "Bulgaria",
    "BHR": "Bahrain",
    "BHS": "Bahamas",
    "BIH": "Bosnia and Herzegovina",
    "BLM": "Saint Barthélemy",
    "BLR": "Belarus",
    "BLZ": "Belize",
    "BMU": "Bermuda",
    "BOL": "Bolivia",
    "BRA": "Brazil",
    "BRB": "Barbados",
    "BRN": "Brunei",
    "BTN": "Bhutan",
    "BVT": "Bouvet Island",
    "BWA": "Botswana",
    "CAF": "Central African Republic",
    "CAN": "Canada",
    "CCK": "Cocos (Keeling) Islands",
    "CHE": "Switzerland",
    "CHL": "Chile",
    "CHN": "China",
    "CIV": "Côte d’Ivoire",
    "CMR": "Cameroon",
    "COD": "Democratic Republic of the Congo",
    "COG": "Congo",
    "COK": "Cook Islands",
    "COL": "Colombia",
    "COM": "Comoros",
    "CPT": "Clipperton",
    "CPV": "Cabo Verde",
    "CRI": "Costa Rica",
    "CUB": "Cuba",
    "CUW": "Curaçao",
    "CXR": "Christmas Island",
    "CYM": "Cayman Islands",
    "CYP": "Cyprus",
    "CZE": "Czechia",
    "DEU": "Germany",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DNK": "Denmark",
    "DOM": "Dominican Republic",
    "DZA": "Algeria",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "ERI": "Eritrea",
    "ESH": "Western Sahara",
    "ESP": "Spain",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "FIN": "Finland",
    "FJI": "Fiji",
    "FLK": "Falkland Islands",
    "FRA": "France",
    "FRO": "Faroes",
    "FSM": "Micronesia",
    "GAB": "Gabon",
    "GBR": "United Kingdom",
    "GEO": "Georgia",
    "GGY": "Guernsey",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GIN": "Guinea",
    "GMB": "The Gambia",
    "GNB": "Guinea-Bissau",
    "GNQ": "Equatorial Guinea",
    "GRC": "Greece",
    "GRD": "Grenada",
    "GRL": "Greenland",
    "GTM": "Guatemala",
    "GUM": "Guam",
    "GUY": "Guyana",
    "HKG": "Hong Kong",
    "HMD": "Heard Island and McDonald Islands",
    "HND": "Honduras",
    "HRV": "Croatia",
    "HTI": "Haiti",
    "HUN": "Hungary",
    "IDN": "Indonesia",
    "IMN": "Isle of Man",
    "IND": "India",
    "IOT": "British Indian Ocean Territory",
    "IRL": "Ireland",
    "IRN": "Iran",
    "IRQ": "Iraq",
    "ISL": "Iceland",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JEY": "Jersey",
    "JOR": "Jordan",
    "JPN": "Japan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KGZ": "Kyrgyzstan",
    "KHM": "Cambodia",
    "KIR": "Kiribati",
    "KNA": "Saint Kitts and Nevis",
    "KOR": "South Korea",
    "KWT": "Kuwait",
    "LAO": "Laos",
    "LBN": "Lebanon",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LCA": "Saint Lucia",
    "LIE": "Liechtenstein",
    "LKA": "Sri Lanka",
    "LSO": "Lesotho",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "LVA": "Latvia",
    "MAC": "Macao",
    "MAF": "Saint Martin",
    "MAR": "Morocco",
    "MCO": "Monaco",
    "MDA": "Moldova",
    "MDG": "Madagascar",
    "MDV": "Maldives",
    "MEX": "Mexico",
    "MHL": "Marshall Islands",
    "MKD": "North Macedonia",
    "MLI": "Mali",
    "MLT": "Malta",
    "MMR": "Myanmar/Burma",
    "MNE": "Montenegro",
    "MNG": "Mongolia",
    "MNP": "Northern Mariana Islands",
    "MOZ": "Mozambique",
    "MRT": "Mauritania",
    "MSR": "Montserrat",
    "MUS": "Mauritius",
    "MWI": "Malawi",
    "MYS": "Malaysia",
    "NAM": "Namibia",
    "NCL": "New Caledonia",
    "NER": "Niger",
    "NFK": "Norfolk Island",
    "NGA": "Nigeria",
    "NIC": "Nicaragua",
    "NIU": "Niue",
    "NLD": "Netherlands",
    "NOR": "Norway",
    "NPL": "Nepal",
    "NRU": "Nauru",
    "NZL": "New Zealand",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PCN": "Pitcairn Islands",
    "PER": "Peru",
    "PHL": "Philippines",
    "PLW": "Palau",
    "PNG": "Papua New Guinea",
    "POL": "Poland",
    "PRI": "Puerto Rico",
    "PRK": "North Korea",
    "PRT": "Portugal",
    "PRY": "Paraguay",
    "PSE": "Palestine",
    "PYF": "French Polynesia",
    "QAT": "Qatar",
    "ROU": "Romania",
    "RUS": "Russia",
    "RWA": "Rwanda",
    "SAU": "Saudi Arabia",
    "SDN": "Sudan",
    "SEN": "Senegal",
    "SGP": "Singapore",
    "SGS": "South Georgia and the South Sandwich Islands",
    "SHN": "Saint Helena, Ascension and Tristan da Cunha",
    "SJM": "Svalbard and Jan Mayen",
    "SLB": "Solomon Islands",
    "SLE": "Sierra Leone",
    "SLV": "El Salvador",
    "SMR": "San Marino",
    "SOM": "Somalia",
    "SPM": "Saint Pierre and Miquelon",
    "SRB": "Serbia",
    "SSD": "South Sudan",
    "STP": "São Tomé and Príncipe",
    "SUR": "Suriname",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SWE": "Sweden",
    "SWZ": "Eswatini",
    "SXM": "Sint Maarten",
    "SYC": "Seychelles",
    "SYR": "Syria",
    "TCA": "Turks and Caicos Islands",
    "TCD": "Chad",
    "TGO": "Togo",
    "THA": "Thailand",
    "TJK": "Tajikistan",
    "TKL": "Tokelau",
    "TKM": "Turkmenistan",
    "TLS": "Timor-Leste",
    "TON": "Tonga",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Türkiye",
    "TUV": "Tuvalu",
    "TWN": "Taiwan",
    "TZA": "Tanzania",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "UMI": "United States Minor Outlying Islands",
    "URY": "Uruguay",
    "USA": "United States",
    "UZB": "Uzbekistan",
    "VAT": "Holy See",
    "VCT": "Saint Vincent and the Grenadines",
    "VEN": "Venezuela",
    "VGB": "British Virgin Islands",
    "VIR": "US Virgin Islands",
    "VNM": "Viet Nam",
    "VUT": "Vanuatu",
    "WLF": "Wallis and Futuna",
    "WSM": "Samoa",
    "XKX": "Kosovo",
    "YEM": "Yemen",
    "ZAF": "South Africa",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe",
}


# Alias usuels NON officiels (formes courtes/historiques rencontrees dans la
# presse et les annonces), qui completent le referentiel officiel. Notamment
# "irak" : la forme UE officielle est "Iraq", mais les sources FR ecrivent
# souvent "Irak" -> on couvre les deux.
ALIAS = {
    "irak": "IRQ",
    "rdc": "COD", "congo kinshasa": "COD", "congo democratique": "COD",
    "congo brazzaville": "COG",
    "usa": "USA", "etats unis d amerique": "USA",
    "uk": "GBR", "grande bretagne": "GBR", "angleterre": "GBR",
    "coree du nord": "PRK", "coree du sud": "KOR",
    "birmanie": "MMR",
    "emirats arabes unis": "ARE", "uae": "ARE",
    "centrafrique": "CAF",
    "cap vert": "CPV",
    "tchequie": "CZE",
}


def _normaliser(s):
    """minuscule, sans accents, ponctuation -> espace, espaces reduits."""
    s = str(s or "").strip().lower()
    s = "".join(ch for ch in unicodedata.normalize("NFD", s)
                if unicodedata.category(ch) != "Mn")
    s = "".join(ch if ch.isalnum() else " " for ch in s)
    return " ".join(s.split())


# Index inverse : forme normalisee -> ISO3, depuis EN puis FR (qui prime) puis
# ALIAS. Construit une fois au chargement du module.
_INDEX = {}
for _c, _n in PAYS_EN.items():
    _INDEX.setdefault(_normaliser(_n), _c)
for _c, _n in PAYS_FR.items():
    _INDEX[_normaliser(_n)] = _c
for _forme, _c in ALIAS.items():
    _INDEX.setdefault(_normaliser(_forme), _c)


def resoudre(valeur):
    """nom (FR/EN/alias) ou code ISO3 -> ISO3, ou None si inconnu.

    Un code ISO3 valide et connu est renvoye tel quel ; sinon on normalise
    (accents + casse + ponctuation) et on cherche dans l'index."""
    v = str(valeur or "").strip()
    if not v:
        return None
    code = v.upper()
    if len(code) == 3 and code.isalpha() and code in PAYS_FR:
        return code
    return _INDEX.get(_normaliser(v))


def nom_fr(iso3):
    """Libelle FR officiel d'un ISO3 (fallback : le code lui-meme)."""
    return PAYS_FR.get(str(iso3 or "").upper(), str(iso3 or ""))


def noms_pour(iso3):
    """Formes lower d'un pays (FR accentue, FR sans accent, EN) pour reperer
    une mention dans du texte. Set vide si l'ISO3 est inconnu."""
    c = str(iso3 or "").upper()
    formes = set()
    for source in (PAYS_FR.get(c), PAYS_EN.get(c)):
        if source:
            formes.add(source.strip().lower())
            formes.add(_normaliser(source))
    return {f for f in formes if f}
